name: "Warema WMS Bridge (Python)"
description: "Controls Warema WMS blinds via USB Stick - MQTT bridge"
version: "1.0.9"
slug: "warema_wms_py"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
homeassistant_api: false
hassio_api: true
host_network: false
uart: true
usb: true
services:
  - mqtt:want
map:
  - share:rw

options:
  wms_serial_port: "/dev/ttyUSB0"
  wms_channel: 17
  wms_pan_id: "FFFF"
  wms_key: "00112233445566778899AABBCCDDEEFF"
  polling_interval: 30
  moving_interval: 1
  mqtt_user: ""
  mqtt_password: ""
  log_level: "info"

schema:
  wms_serial_port: str
  wms_channel: int
  wms_pan_id: str
  wms_key: str
  polling_interval: int
  moving_interval: int
  ignored_devices: str?
  force_devices: str?
  mqtt_user: str?
  mqtt_password: str?
  log_level: list(debug|info|warning|error)
